{
  "comments": [
    {
      "key": {
        "uuid": "85cd9207_986a6e89",
        "filename": "a1/data.py",
        "patchSetId": 4
      },
      "lineNbr": 61,
      "author": {
        "id": 1000002
      },
      "writtenOn": "2019-10-16T05:16:31Z",
      "side": 1,
      "message": "You can use different function names in SDL wrapper but just a note that python SDL api function what deletes a key is:\ndef remove(self, ns, keys)\n-keys is a set (or a list, not sure yet which type we choose)\n-Won\u0027t return anything",
      "revId": "7cec82d95d4b9d18c42b103eb14d39f94fcd0776",
      "serverId": "84e4e190-e623-4c37-9eda-58b1937c1b53",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "644a0b64_ea4f7a8a",
        "filename": "a1/data.py",
        "patchSetId": 4
      },
      "lineNbr": 119,
      "author": {
        "id": 1000002
      },
      "writtenOn": "2019-10-16T05:16:31Z",
      "side": 1,
      "message": "If you need to find only keys from SDL, you can also use SDL find_keys() method.\ndef find_keys(self, ns, key_prefix)\n-returns a list of matching keys. If no match, empty list is returned.",
      "revId": "7cec82d95d4b9d18c42b103eb14d39f94fcd0776",
      "serverId": "84e4e190-e623-4c37-9eda-58b1937c1b53",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "c6fc3937_5c2bf6d3",
        "filename": "a1/data.py",
        "patchSetId": 4
      },
      "lineNbr": 159,
      "author": {
        "id": 1000037
      },
      "writtenOn": "2019-10-15T15:30:47Z",
      "side": 1,
      "message": "Naive question because I don\u0027t usually work in try/catch|except worlds....\n\nGiven your comment above about not wanting to blow up anything, what happens if SDL tosses an exception that you don\u0027t have explicitly listed?  Doesn\u0027t that cause a panic?  If so, would it be better to catch any failure, logging anything that you don\u0027t know about/expect, and then moving on so as not to take the application down?",
      "revId": "7cec82d95d4b9d18c42b103eb14d39f94fcd0776",
      "serverId": "84e4e190-e623-4c37-9eda-58b1937c1b53",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "41ef565a_7fb69d1b",
        "filename": "a1/data.py",
        "patchSetId": 4
      },
      "lineNbr": 159,
      "author": {
        "id": 1000037
      },
      "writtenOn": "2019-10-15T15:36:28Z",
      "side": 1,
      "message": "Ack and thanks.",
      "parentUuid": "c6fc3937_5c2bf6d3",
      "revId": "7cec82d95d4b9d18c42b103eb14d39f94fcd0776",
      "serverId": "84e4e190-e623-4c37-9eda-58b1937c1b53",
      "unresolved": false
    }
  ]
}