{
  "comments": [
    {
      "key": {
        "uuid": "cc0be6f9_abc50c0d",
        "filename": "a1/data.py",
        "patchSetId": 2
      },
      "lineNbr": 54,
      "author": {
        "id": 1000002
      },
      "writtenOn": "2020-01-02T20:15:36Z",
      "side": 1,
      "message": "SDL Error handling (exceptions) is missing here and below SDL API calls?",
      "revId": "86becdaaad5b1d069a6b99f55876149b658d4d39",
      "serverId": "84e4e190-e623-4c37-9eda-58b1937c1b53",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "add8182d_f2d8637a",
        "filename": "integration_tests/dbaas-service/Chart.yaml",
        "patchSetId": 2
      },
      "lineNbr": 1,
      "author": {
        "id": 1000002
      },
      "writtenOn": "2020-01-02T20:15:36Z",
      "side": 1,
      "message": "Not sure about this but how about the year, should it be now 2020 or still 2019?",
      "revId": "86becdaaad5b1d069a6b99f55876149b658d4d39",
      "serverId": "84e4e190-e623-4c37-9eda-58b1937c1b53",
      "unresolved": true
    }
  ]
}